server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: order
