#配置端口号
server:
  port: 8001

#配置spring信息
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db03?useSSL=FALSE&serverTimezone=UTC&allowPublicKeyRetrieval=TRUE
    username: root
    password: 123456

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.su.springcloud.entities

#eureka
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #Eureka服务端在收到最后一次心跳后等待时间的上限，单位为秒（默认90），超时将剔除服务
    lease-expiration-duration-in-seconds: 2
      #Eureka客户端向服务器发送心跳的时间间隔，单位为秒（默认为30）
    lease-renewal-interval-in-seconds: 1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/
      defaultZone: http://eureka1:7001/eureka/
