server:
  port: 8401

spring:
  cloud:
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用自动从8719开始依次+1扫描，直到找到未被占用的地址
        port: 8719
  application:
    name: cloudalibaba-sentinel-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
