server:
  port: 9527


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1:7001/eureka


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                     #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh                  #路由的id，没有固定的规则但是要求唯一，建议配合服务名
          uri: lb://cloud-payment-service
          #uri: http://localhost:8001         #匹配后提供服务的地址
          predicates:
            - Path=/payment/get/**           #断言，路径相匹配的进行路由
            #- Query=username, /d            #要有参数名为username并且值为整数
            #- Method=GET                    #必须为GEt请求
            #- Header=X-Request -Id, /d+     #请求头要含有X-Request -Id属性并且值为整数的正则表达式。
            #- Cookie=username,sdh           #Cookie中username为sdh的
            #- After=2020-11-03T14:25:04.299+08:00[Asia/Shanghai]   在时间之后   before是之前

        - id: payment_routh2                  #路由的id，没有固定的规则但是要求唯一，建议配合服务名
          uri: lb://cloud-payment-service
          #uri: http://localhost:8001         #匹配后提供服务的地址
          predicates:
            - Path=/payment/lb           #断言，路径相匹配的进行路由
